version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    networks: 
      - log-network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    networks: 
      - log-network
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
  
  api:
    build: .
    ports: 
      - "5000:80"
    environment: 
      ELASTIC_URL: http://elasticsearch:9200
    depends_on: 
      - kibana
      - elasticsearch
    networks: 
      - log-network

networks:
  log-network:
    driver: bridge
